### ISSUE TITLE
Can't compile Sketch in Aruduino 1.8.13 - exit status 1 'class PushButton' has no member named 'onHold'

### ISSUE THREAD

**Issue by gsargent70** [mattogodoy/mighty-mouse#1]
When trying to compile the sketch get the error in the title.  Info for setup as follows

Arduino IDE: 1.8.13
Adafruit GFX Library 1.10.4
Adafruit SSD1306 2.4.2
Bounce 2 2.55.0
r89m Buttons 2.0.1
r89m PushButton 1.0.1
Board: Arduino Leonardo

**Comment by mattogodoy** [comment]
That's strange. `onHold` is in fact one of the capabilities of the `r89m PushButton` library (see [docs](https://github.com/r89m/PushButton)).

It seems this is a library issue, but as I can see from the list you posted you have all the required libraries installed (even the ones required for `PushButton` as stated in the docs).

I would uninstall `Bounce 2`, `r89m Buttons` and `r89m PushButton`. Reinstall all of them again and try again.

Another thing to notice is that I use VSCode with PlatformIO as an IDE. It has a small learning curve, but it's way better than the Arduino IDE.

Please let me know if you could solve this.

**Comment by mattogodoy** [comment]
I'm closing this issue under the assumption that this is working.
