### ISSUE TITLE
Manage patent risks?

### ISSUE THREAD

**Issue by KantarBruceAdams** [mattogodoy/mighty-mouse#2]
This is a great project idea. Have you considered how to avoid infringing whatever patents 3dconnexion have on their products?
They look overly broad to me (e.g. https://patents.justia.com/assignee/3dconnexion-gmbh) but lawyers and money...

I've seen this video on the internals https://www.youtube.com/watch?v=1R7NCH_1UDI
which looks a good design in many ways and challenging to avoid copying.

**Comment by mattogodoy** [comment]
Thank you!
I am not very concerned about copyright because I have not used any of their IP for this project. I have created software, hardware and electronics myself, all from scratch :)

Thanks for the video, it is really interesting and I had not seen how it works before.
